set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'liamvdvyver/yats'

# Boostrap - install tpm if not already installed
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

set -g @yats-bind "C-s"
set -g @yats-path "$HOME/git"
set -g @yats-exclude ""
set -g @yats-dirs "$HOME/.config/tmux/plugins/yats\n$HOME/.local/share/nvim/lazy/snippits"
set -g @yats-cmds "weechat\nncspot"

# Config taken from https://github.com/tmux-plugins/tmux-sensible:
set -sg escape-time 0
bind-key 'R' source "~/.config/tmux/tmux.conf"
set -g default-terminal "$TERM"

# Change prefix
set-option -g prefix C-b

# send-message "reloaded"

bind-key 'V' run-shell "tmux-find 'nvim'"
bind-key 'S' run-shell "tmux-find 'ncspot'"
bind-key 'P' run-shell "tmux-find 'pdf'"
bind-key 'W' run-shell "tmux-find 'qutebrowser'"
bind-key 'E' run-shell "tmux-find 'ranger'"

# Statusline
set -g status-style fg=default,bg=default
set -g status-justify left
set -g status-position top
set -g status-left '  #[bg=yellow,fg=black]  #S  #[bg=default] '
set -g status-right-length 150
set -g status-left-length 150
set -g status-right '#{prefix_highlight} #[bg=blue,fg=black]  󰁹 #(upower -i /org/freedesktop/UPower/devices/DisplayDevice | grep percentage | sed "s/ *percentage: *\([0-9]\+\).*/\1/") |  #(pulsemixer --get-volume | cut -f 1 -d " ") |  %d %b %y, %H:%M:%S  #[bg=default,fg=default]  '
set-window-option -g window-status-format '   #I #W   '
set-window-option -g window-status-current-format ' #[bg=green,fg=black]  #I #W  #[bg=default] '

set -g status-interval 1

setw -g mouse on

set -g base-index 1

# Scripts
bind-key 'C-f' display-popup -E "ranger"

# Restore clear bind
bind C-h send-keys 'C-h'
bind C-j send-keys 'C-j'
bind C-k send-keys 'C-k'
bind C-l send-keys 'C-l'

bind-key 'N' run-shell "tmux-sessioniser notes"
bind-key 'G' run-shell "tmuxifier load-window sage"

bind-key 'm' swap-pane -t 0\; select-pane -t 0
bind-key 'v' run-shell "tmux-move"

set -g renumber-windows on

# Make ipynb work in nvim
set -gq allow-passthrough on
set -g visual-activity off

set-hook -g after-split-window 'select-layout main-vertical; resize-pane -x 50%'
set-hook -g after-kill-pane    'select-layout main-vertical; resize-pane -x 50%'
set-hook -g pane-exited        'select-layout main-vertical; resize-pane -x 50%'

set -g focus-events on

set-option -w -g aggressive-resize on

run '~/.config/tmux/plugins/tpm/tpm'

run-shell xwmux-tmux-conf.sh
