xrdb ~/.config/X11/Xresources
xset s off &
xset -dpms &

picom -c &
~/.config/arandr.sh &
cat ~/.config/rice/pape | xargs pape &

sxhkd &
mpd &
mpDris2 &
spotifyd &
flameshot &
dunst &
nm-applet &
emacs --daemon &
syncthingtray &
xfce4-power-manager &

exec i3
