#                            __ 
# _ __ ___   ___ ___  _ __  / _|
#| '__/ __| / __/ _ \| '_ \| |_ 
#| | | (__ | (_| (_) | | | |  _|
#|_|  \___(_)___\___/|_| |_|_|  
                              

set show_hidden true

set vcs_backend_git enabled
set vcs_aware true

set preview_images true
set preview_images_method ueberzug

set draw_borders true
set update_tmux_title true
set tilde_in_titlebar true

map <C-t> fzf_select
map <A-d> shell dragon-drop -a -x %p
map - shell nvim -c Oil

map g. cd ~/.config/
map gp cd ~/git/
map gx cd ~/git/scripts/

default_linemode devicons
